-- AlterTable
ALTER TABLE `User` ADD COLUMN `role` VARCHAR(191) NULL,
    MODIFY `mbti` ENUM('INTJ', 'INTP', 'ENTJ', 'ENTP', 'INFJ', 'INFP', 'ENFJ', 'ENFP', 'ISTJ', 'ISFJ', 'ESTJ', 'ESFJ', 'ISTP', 'ISFP', 'ESTP', 'ESFP') NULL;
